//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereToWhere.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public tbl_user()
        {
            this.tbl_directory = new HashSet<tbl_directory>();
            this.tbl_useranswer = new HashSet<tbl_useranswer>();
        }
    
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string ProfileImage { get; set; }
        public string LoginType { get; set; }
        public bool IsEmailVerified { get; set; }
        public string FirebaseToken { get; set; }
        public bool IsActive { get; set; }
        public string DeviceType { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Mobile { get; set; }
        public string Description { get; set; }
        public string Pronouns { get; set; }
    
        public virtual ICollection<tbl_directory> tbl_directory { get; set; }
        public virtual ICollection<tbl_useranswer> tbl_useranswer { get; set; }
    }
}
