//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereToWhere.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_directory
    {
        public long DirId { get; set; }
        public string Name { get; set; }
        public long ParentDirId { get; set; }
        public string DirType { get; set; }
        public long UserId { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
    }
}
