//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereToWhere.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_question
    {
        public tbl_question()
        {
            this.tbl_answer = new HashSet<tbl_answer>();
            this.tbl_useranswer = new HashSet<tbl_useranswer>();
        }
    
        public int QueId { get; set; }
        public string Question { get; set; }
        public string ChoiceType { get; set; }
        public bool IsImageQuestion { get; set; }
    
        public virtual ICollection<tbl_answer> tbl_answer { get; set; }
        public virtual ICollection<tbl_useranswer> tbl_useranswer { get; set; }
    }
}
