//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereToWhere.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_useranswer
    {
        public long UserAnsId { get; set; }
        public long UserId { get; set; }
        public int QueId { get; set; }
        public int AnsId { get; set; }
        public string Comment { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
        public virtual tbl_answer tbl_answer { get; set; }
        public virtual tbl_question tbl_question { get; set; }
    }
}
