//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereToWhere.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_dashboard_post
    {
        public long PostId { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public string ShareType { get; set; }
        public int LikeCount { get; set; }
        public int DislikeCount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public long UserId { get; set; }
    }
}
